---
- name: Install bind9 packages
  apt:
    name: [bind9, bind9utils, bind9-doc]
    update_cache: yes
  become: true

- name: Start service bind9 if not started
  service:
    name: bind9
    state: started
  become: true

- name: Update bind9 options and local file
  template:
    src: "{{ item.src }}"
    dest: "/etc/bind/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: named.conf.options.j2, dest: named.conf.options }
    - { src: named.conf.local.j2, dest: named.conf.local }
  notify: "restart bind9"
  become: true

- name: Create zone dir if it doesn't exist
  file:
    path: /etc/bind/zones
    state: directory
    mode: 0755
  become: true

- name: Create forward zone file
  template:
    src: "{{ item.src }}"
    dest: "/etc/bind/zones/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: db.tiexin.com.j2, dest: db.tiexin.com }
    - { src: db.2.16.172.j2, dest: db.2.16.172 }
  notify: "restart bind9"
  become: true

- name: named-checkconf
  command: named-checkconf
  register: named_checkconf_res
  failed_when: named_checkconf_res.rc != 0
  changed_when: false
  become: true

- name: Check zone
  command: "named-checkzone {{ zone }} /etc/bind/zones/db.{{ zone }}"
  register: named_checkzone_res
  failed_when: named_checkzone_res.rc != 0
  changed_when: false
  become: true

- name: Check reverse zone
  command: "named-checkzone {{ reverse_zone }} /etc/bind/zones/db.{{ reverse_zone }}"
  register: named_checkreverse_zone_res
  failed_when: named_checkreverse_zone_res.rc != 0
  changed_when: false
  become: true

- name: UFW allow bind9
  command: ufw allow Bind9
  become: true
