---
- name: Download shell script to setup nodejs source for node v6
  get_url:
    url: https://deb.nodesource.com/setup_6.x
    dest: /tmp/setup_6.x
    mode: 0755

- name: Execute the setup_6.x
  shell: /tmp/setup_6.x
  become: true

- name: Remove the setup_6.x
  file:
    path: /tmp/setup_6.x
    state: absent

- name: Install node v6
  apt:
    name: nodejs
  become: true
